// English text catalog for Rain Math.
// Keep this file as a plain script, not fetched JSON, so index.html still works
// when opened directly from disk with file://.
globalThis.RainMathText = {
  locale: "en",
  common: {
    back: "Back",
    close: "Close",
    create: "Create",
    play: "Play",
    next: "Next",
  },
  support: {
    label: "Support",
    shortLabel: "Ko-fi",
    welcomeTitle: "Support Rain Math",
    welcomeBody: "Optional: help fund new problem types, polish, and hosting.",
    welcomeLink: "Buy me a coffee on Ko-fi",
  },
  welcome: {
    menuLink: "Menu",
    firstVisitEyebrow: "First visit",
    menuEyebrow: "Menu",
    title: "Rain Math",
    subtitle: "Choose a player, learn the controls, then clear the drops.",
    playerTitle: "Player",
    playerSubtitle: "Progress saves locally in this browser.",
    localPlayer: "Local player",
    playingNow: "Playing now",
    newPlayerPlaceholder: "New player name",
    emptyNameError: "Enter a player name.",
    playAs: "Play as {playerName}",
    actionSubtitle: "Start immediately, or take the guided tour first.",
    tutorial: "Tutorial",
    fullLoginMenu: "Full Login Menu",
    ariaLabel: "Rain Math menu",
  },
  tutorial: {
    ariaLabel: "Rain Math tutorial",
    progressLabel: "{kicker} - {current}/{total}",
    skipToPlay: "Skip to Play",
    steps: [
      {
        target: ".op-chits",
        kicker: "Start here",
        title: "Choose problem types to work on.",
        body: "Turn problem types on and off while the game is running. Arithmetic and x10 can mix; Shapes, SI, and factoring stay in their own lanes so answers do not collide.",
        tip: "",
      },
      {
        target: ".game",
        kicker: "The playfield",
        title: "Read the drop, type the answer.",
        body: "Most answers clear immediately as soon as the typed value matches. If a drop has the same answer as another, the game avoids showing both at once where that would be confusing.",
        tip: "",
      },
      {
        target: ".input-bar",
        kicker: "Typing rules",
        title: "Some answers use Enter.",
        body: "SI conversions use answers like *1000 or /100 and need Enter. Prime factorization accepts full answers like 2^2*3 plus Enter, or Tab to target a drop and factor it step by step.",
        tip: "",
      },
      {
        target: ".play-controls-card",
        kicker: "Pressure",
        title: "Tune speed and crowding separately.",
        body: "Speed changes how fast drops fall. Drops changes how many can be active at once. Lower either one if the board feels stressful; raise them when practice feels too easy.",
        tip: "",
      },
      {
        target: "#diffCards",
        kicker: "Mastery",
        title: "Each operation has its own level and grid.",
        body: "The level card shows Mastered %. The Grid opens per-problem history: black means unseen, hue shows accuracy, and brightness shows how much evidence the game has.",
        tip: "Boss unlocks when enough current-level problems are mastered.",
      },
      {
        target: ".game",
        kicker: "Breather",
        title: "Spacebar gives a board-clearing pause.",
        body: "Press Space during normal practice to stop new drops and freeze the visible ones. Solve what is on screen, and normal play resumes automatically.",
        tip: "",
      },
      {
        target: ".diff-cards",
        kicker: "Boss mode",
        title: "Beat the boss to move up.",
        body: "When Mastered reaches the unlock threshold, start a boss attempt. Wave 1 tests speed, Wave 2 tests simultaneous load, and the mothership tests all of the current level's problems.",
        tip: "Wave and Blitz scores are simply problems solved. Mother ship is time until complete.",
      },
      {
        target: ".version",
        kicker: "Profiles",
        title: "Use local players and Results.",
        body: "Profiles live in this browser's localStorage for now. Use Login to switch players, Results to inspect progress, and Menu to revisit this tutorial.",
        tip: "This is local-only.",
      },
    ],
  },
};
