// English text catalog for Rain Math. ES module — loaded over HTTP (the app is
// served via `npm start` / GitHub Pages), not fetched JSON.
export const RainMathText = {
  locale: "en",
  common: {
    back: "Back",
    close: "Close",
    create: "Create",
    play: "Play",
    next: "Next",
    finish: "Finish",
  },
  support: {
    label: "Donate",
    shortLabel: "Donate",
    welcomeTitle: "No ads · No tracking · No sign-in",
    welcomeBody: "Rain Math runs entirely in your browser — no server, no accounts, nothing collected about you. Thank you for your donations.",
    welcomeLink: "Donate",
  },
  welcome: {
    menuLink: "Menu",
    firstVisitEyebrow: "First visit",
    menuEyebrow: "Menu",
    title: "Rain Math",
    subtitle: "Start playing, take the tour, or manage local players.",
    playerTitle: "Player",
    playerSubtitle: "Progress saves locally in this browser. Use Login to switch, create, delete, clear, back up, or restore players.",
    currentPlayer: "Current player: {playerName}",
    localPlayer: "Local player",
    playingNow: "Playing now",
    newPlayerPlaceholder: "New player name",
    emptyNameError: "Enter a player name.",
    playAs: "Play as {playerName}",
    actionSubtitle: "Start immediately, or take the guided tour first.",
    tutorial: "Tutorial",
    testMe: "Test Me",
    fullLoginMenu: "Switch / manage players",
    ariaLabel: "Rain Math menu",
  },
  placement: {
    ariaLabel: "Rain Math placement test",
    title: "Test Me",
    subtitle: "Pick a problem type. Test Me runs like the regular game, one falling problem at a time, to find a reasonable starting level.",
    note: "Missed problems repeat soon. Accepting a higher level marks lower-level facts as placed out only until real attempts take over.",
  },
  tutorial: {
    ariaLabel: "Rain Math tutorial",
    progressLabel: "{kicker} - {current}/{total}",
    skipToPlay: "Skip to Play",
    steps: [
      {
        target: ".op-chits",
        kicker: "Start here",
        title: "Choose problem types to work on.",
        body: "Turn problem types on and off while the game is running. Arithmetic and x10 can mix; Rounding, Shapes, SI, Powers & Roots, and factoring stay in their own lanes so answers do not collide.",
        tip: "",
      },
      {
        target: ".game",
        kicker: "The playfield",
        title: "Read the drop, type the answer.",
        body: "Most answers clear immediately as soon as the typed value matches, including rounding prompts like 47 ≈ 10. If a drop has the same answer as another, the game avoids showing both at once where that would be confusing.",
        tip: "",
      },
      {
        target: ".input-bar",
        kicker: "Typing rules",
        title: "Some answers use Enter.",
        body: "SI conversions use answers like *1000 or /100 and need Enter. Prime factorization accepts full answers like 2^2*3 plus Enter, or Tab to target a drop and factor it step by step. Tab and Shift+Tab switch factor targets.",
        tip: "If you fire too many impossible answers quickly, the cannon briefly overloads — faster on levels with only a few possible answers. Editing and partial answers do not count.",
      },
      {
        target: ".play-controls-card",
        kicker: "Pressure",
        title: "Tune speed, crowding, and text size.",
        body: "Speed changes how fast drops fall. Drops changes how many can be active at once. Text changes the size of problems on drops and worksheet nodes. Lower pressure if the board feels stressful; raise it when practice feels too easy.",
        tip: "",
      },
      {
        target: "#diffCards",
        kicker: "Mastery",
        title: "Each operation has its own level and grid.",
        body: "The level card shows Mastered %. The Grid opens per-problem history: black means unseen, hue shows accuracy, and brightness shows how much evidence the game has.",
        tip: "Practice is weighted toward unseen and weaker problems. Level choices unlock when all current-level problems are mastered — or when Test Me places you at a higher starting level.",
      },
      {
        target: ".game",
        kicker: "Breather",
        title: "Spacebar gives a board-clearing pause.",
        body: "Press Space during normal practice to stop new drops and freeze the visible ones. Solve what is on screen, and normal play resumes automatically.",
        tip: "",
      },
      {
        target: ".diff-cards",
        kicker: "Boss mode",
        title: "Mastery unlocks choices.",
        body: "When Mastered reaches 100%, you can keep practicing, move to the next level, or try boss mode. Blitz tests speed, Wave tests simultaneous load, and Worksheet tests every problem in the level.",
        tip: "Blitz records survival time, Wave records the most problems handled at once, and Worksheet records time until complete.",
      },
      {
        target: ".version",
        kicker: "Profiles",
        title: "Use local players, Test Me, Log, and Finish.",
        body: "Profiles live in this browser's localStorage for now. Use Login to switch, create, delete, clear, back up, or restore players. Use Test Me to choose a starting level, Grid to inspect mastery, and Log to review recent sessions.",
        tip: "Finish stops new drops and opens this sitting's Report to share. Brief reloads continue the same session; a long break or player switch starts a new one.",
      },
    ],
  },
};
